/**
 * Created on 2025/8/26
 */
package ohos_app_cangjie_entry.constants

internal import ohos.base.*

public class CommonStyleConstants {
    /**
     * FULL SIZE
     */
    public static let FULL_SIZE: Length = 100.percent
     /**
     * Pad TBLR
     */
    public static let PAGE_PAD:Int64  = 12;
    /**
     * Pad LR
     */
    public static let PAGE_PAD_LR:Int64  = 12;
     /**
     * Pad TB
     */
    public static let PAGE_PAD_TB:Int64  = 12;

    /**
    * Login Header Height
    */
    public static let LOGIN_HEAD_SIZE:Length = 23.percent
    /**
    * Input Logo
    */
    public static let LOGIN_INPUT_LOGO_WH:Length = 25.vp
    /**
    * Logo Input PlaceHold Font
    */
    public static let LOGIN_PLACEHOLD_FONT: Int64 = 16
     /**
      * Input W
     */
    public static let LOGIN_INPUT_WIDTH:Length = 85.percent
    /**
     * Input H
     */
    public static let LOGIN_INPUT_HEIGHT:Length = 30.vp
    /**
     * Input Font
     */
    public static let LOGIN_INPUT_FONT:Int64 = 16

}