export default class CommonGlobalConstants{
  //1.AppProjectName
  public static AppProjectName = 'appProjectName'

  //2.BaseUrl
  public static BaseUrl = 'baseUrl'

  //3.AppEnv
  public static AppEnv = 'env'

  //4.Cookie
  public static Cookie = 'cookie'

  //5.UserName
  public static UserName = 'userName'

  //6.UserId
  public static UserId = 'userId'

  //7.isOffline
  public static IsOffline = 'isOffline'

  //8. AppVersion
  public static AppVersion = 'appVersion'

  //9. CameraCompress 照片压缩系数
  public static CameraCompress = 'cameraCompress'

  //10.TenantId 租户 id
  public static TenantId = 'TenantId'

  //11.LaunchVersion
  public static LaunchVersion = 'LaunchVersion'

  //12.状态栏颜色
  public static StatusBarColor = 'StatusBarColor'

  //13.状态栏文字颜色
  public static StatusFontColor = 'StatusBarColor'

  //14.服务器时间
  public static ServerTime = 'ServerTime'

  //15.CPU运行周期
  public static OpenTimeUntilNow = 'OpenTimeUntilNow'

  // 16.文件地址
  public static OpenFileHost = 'fileHost'

  // 17.缩略图地址
  public static ThumbnailHost = 'thumbnailHost'

  //18.分销规则key
  static readonly ProdSpec_Key = "PRODSPEC";


}