export default class CommonTableNameConstants{
  /**
   * 进离店表名字
   */
  static readonly VISIT_INOUT_STORE_TABLE: string = 'visit_inout_store';

  /**
   * 拜访状态表
   */
  static readonly VISIT_STORE_STATUS_TABLE: string = 'visit_store_status';
  /**
   * 门店表名字
   */
  static readonly BASE_TABLE = 'base_store';
  /**
   * 问卷表名字
   */
  static readonly  BASE_ACVT = 'base_acvt'
  /**
   * 问题表名字
   */
  static readonly  BASE_ACVT_QST = 'base_acvt_qst'
  /**
   * 问题表opt名字
   */
  static readonly  BASE_ACVT_QST_OPT = 'base_acvt_qst_opt'
  /**
   * 菜单表名字
   */
  static readonly  BASE_FUNCS = 'base_funcs'
  /**
   * 回显表名字
   */
  static readonly  BASE_STORE_ACVT_DIS = 'base_store_acvt_dis'
  /**
   * 产品表名字
   */
  static readonly  BASE_PRODUCT = 'base_product'

}